apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres 
    url: postgres:5432
    database: db  
    user: user 
    secureJsonData:
      password: root 
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true